config/routes.rb
Rails.application.routes.draw do
  resources :clothings
  resources :clearance_batches, only: [:index, :create] do
    resources :items, only: [:index]
  end
  resources :items
  root to: "clearance_batches#index"

  get  'report/:id', to: 'clearance_batches#report', as: :report
  get  'report_pdf/:id', to: 'clearance_batches#report_pdf', as: :pdf
  get  'manual_input', to: 'clearance_batches#manual_input', as: :manual_input
  post 'process_manual', to: 'clearance_batches#process_manual', as: :process_manual
end

app/models/clearance_batch.rb
class ClearanceBatch < ActiveRecord::Base

  has_many :items

end

app/models/clothing.rb
class Clothing < ActiveRecord::Base
  # I didn't put the dress/pants $5.0, everything else $2.0 in here because it doesn't seem very sustainable.
  validates :minimum, allow_nil: false, minimum: true
end

app/models/item.rb
class Item < ActiveRecord::Base

  CLEARANCE_PRICE_PERCENTAGE  = BigDecimal.new("0.75")

  belongs_to :style
  belongs_to :clearance_batch

  validates :status, inclusion: { in: ['sellable', 'not sellable', 'sold', 'clearanced'],
                                  message: "%{value} is not a valid status" }

  scope :sellable, -> { where(status: 'sellable') }

  def clearance!
    regular_clearance = style.wholesale_price * CLEARANCE_PRICE_PERCENTAGE
    minimum_clearance = style.clothing.minimum
    update_attributes!(status: 'clearanced', 
                       price_sold: [regular_clearance, minimum_clearance].max)
  end

end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :items
  belongs_to :clothing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance_batches_controller.rb
class ClearanceBatchesController < ApplicationController
  before_action :set_batch, only: [:report, :report_pdf]

  def index
    @clearance_batches  = ClearanceBatch.all
  end

  def create
    process_batch(params[:csv_batch_file].tempfile)
  end

  def report
  end

  def report_pdf
    html = render_to_string "clearance_batches/report", :layout => 'layouts/pdf', encoding: "UTF-8"
    html.gsub!('<a class="pdf-hide" href="/report_pdf/1">Create PDF</a>', '')

    report = WickedPdf.new.pdf_from_string(html)

    send_data(report, :filename => "Batch ID#{@batch.id}.pdf", :type => 'application/pdf')
  end

  def manual_input

  end

  def process_manual
    ids = params['ids']
    id_array = ids.split(',')

    valid = id_array.all? {|i| is_number?(i) }

    if valid && !ids.empty?
      process_batch(id_array)
    else
      flash.now[:error] = 'Invalid input. Please only put item IDs and commas.'
      render :manual_input
    end
  end

  private

  def process_batch(batch)
    clearancing_status = ClearancingService.new.process_file(batch)
    clearance_batch    = clearancing_status.clearance_batch
    alert_messages     = []
    if clearance_batch.persisted?
      flash[:notice]  = "#{clearance_batch.items.count} items clearanced in batch #{clearance_batch.id}"
    else
      alert_messages << "No new clearance batch was added"
    end
    if clearancing_status.errors.any?
      alert_messages << "#{clearancing_status.errors.count} item ids raised errors and were not clearanced"
      clearancing_status.errors.each {|error| alert_messages << error }
    end
    flash[:alert] = alert_messages.join("<br/>") if alert_messages.any?
    redirect_to action: :index
  end

  def set_batch
    @batch = ClearanceBatch.includes(items: [:style]).find(params[:id])
  end

  def is_number?(object)
    true if Integer(object) rescue false
  end
end

app/controllers/clothings_controller.rb
class ClothingsController < ApplicationController
  before_action :set_clothing, only: [:show, :edit, :update, :destroy]

  # GET /clothings
  def index
    @clothings = Clothing.all
  end

  # GET /clothings/1
  def show
  end

  # GET /clothings/new
  def new
    @clothing = Clothing.new
  end

  # GET /clothings/1/edit
  def edit
  end

  # POST /clothings
  def create
    @clothing = Clothing.new(clothing_params)

    if @clothing.save
      redirect_to @clothing, notice: 'Clothing was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clothings/1
  def update
    if @clothing.update(clothing_params)
      redirect_to @clothing, notice: 'Clothing was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clothings/1
  def destroy
    @clothing.destroy
    redirect_to clothings_url, notice: 'Clothing was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clothing
      @clothing = Clothing.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def clothing_params
      params.require(:clothing).permit(:name, :minimum)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all.includes(:style)

    if params[:clearance_batch_id]
      @items = Item.where(clearance_batch_id: params[:clearance_batch_id])
    end
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:id, :size, :color, :status, :price_sold, :sold_at, :style_id, :clearance_batch_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothings_helper.rb
module ClothingsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def clothing_select
    clothings = Clothing.all
    array = []
    clothings.each do |clothing|
      array << [clothing.name, clothing.id]
    end
    array
  end
end

app/views/clearance_batches/index.html.erb
<h2>Clearance Batches</h2>

<%= form_tag(clearance_batches_path, multipart: true, class: 'form-inline', role: 'form') do %>
    <div class="form-group">
      <%= label_tag 'csv_batch_file', 'Select batch file' %>
      <%= file_field_tag 'csv_batch_file', class: 'form-control' %>
    </div>
    <%= button_tag 'upload batch file', class: 'btn btn-primary' %>
<% end %>

<table class="table table-striped clearance_batches">
  <thead>
  <tr>
    <th></th>
    <th>Date clearanced</th>
    <th>Number of items clearanced</th>
    <th>Report</th>
  </tr>
  </thead>
  <tbody>
  <%- @clearance_batches.each do |clearance_batch| -%>
      <tr>
        <td><%= link_to "Clearance Batch #{clearance_batch.id}", clearance_batch_items_path(clearance_batch.id)%></td>
        <td><%= l(clearance_batch.created_at, format: :short) %></td>
        <td><%= clearance_batch.items.count %></td>
        <td><%= link_to 'Report', report_path(clearance_batch) %></td>
      </tr>
  <%- end -%>
  </tbody>
</table>

app/views/clearance_batches/manual_input.html.haml
.row.text-center
  %h1 Custom Clearance Input

  %p Input the item ideas in the box below seperated by commas.

.row
  .col-md-6.col-md-offset-3.text-center
    = form_tag(process_manual_path, method: :post) do
      %fieldset.form-group
        %label Item IDs
        = text_area_tag 'ids', nil, rows: 10, class: 'form-control'
      %button{ type: 'submit', class: 'btn btn-primary' } Upload

app/views/clearance_batches/report.html.haml
%h1= "Clearance Report for #{@batch.id} (#{l(@batch.created_at, format: :short)})"
%p=  link_to 'Create PDF' ,'#', class: 'pdf-hide'
%table.table.table-striped.table-bordered
  %thead
    %tr
      %th ID
      %th Size
      %th Color
      %th Price
      %th Style
  %tbody
    - @batch.items.each do |item|
      %tr
        %td= item.id
        %td= item.size
        %td= item.color
        %td= number_to_currency(item.price_sold)
        %td= item.style.name

app/views/clothings/_form.html.erb
<%= form_for(@clothing) do |f| %>
  <% if @clothing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clothing.errors.count, "error") %> prohibited this clothing from being saved:</h2>

      <ul>
      <% @clothing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :minimum %><br>
    <%= f.text_field :minimum %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clothings/edit.html.erb
<h1>Editing Clothing</h1>

<%= render 'form' %>

<%= link_to 'Show', @clothing %> |
<%= link_to 'Back', clothings_path %>

app/views/clothings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clothings</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Minimum Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clothings.each do |clothing| %>
      <tr>
        <td><%= clothing.name %></td>
        <td><%= number_to_currency(clothing.minimum) %></td>
        <td><%= link_to 'Show', clothing %></td>
        <td><%= link_to 'Edit', edit_clothing_path(clothing) %></td>
        <td><%= link_to 'Destroy', clothing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clothing', new_clothing_path %>

app/views/clothings/new.html.erb
<h1>New Clothing</h1>

<%= render 'form' %>

<%= link_to 'Back', clothings_path %>

app/views/clothings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @clothing.name %>
</p>
<p>
  <strong>Minimum:</strong>
  <%= @clothing.minimum %>
</p>

<%= link_to 'Edit', edit_clothing_path(@clothing) %> |
<%= link_to 'Back', clothings_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :price_sold %><br>
    <%= f.text_field :price_sold %>
  </div>
  <div class="field">
    <%= f.label :sold_at %><br>
    <%= f.text_field :sold_at %>
  </div>
  <div class="field">
    <%= f.label :style_id %><br>
    <%= f.select :style_id, options_for_select(clothing_select) %>
  </div>
  <div class="field">
    <%= f.label :clearance_batch_id %><br>
    <%= f.number_field :clearance_batch_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table id="items-index-table" class="table dataTable">
  <thead>
    <tr>
      <th>Id</th>
      <th>Size</th>
      <th>Color</th>
      <th>Status</th>
      <th>Price sold</th>
      <th>Sold at</th>
      <th>Style</th>
      <th>Clearance batch</th>
      <th>Item Details</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.size %></td>
        <td><%= item.color %></td>
        <td><%= item.status %></td>
        <td><%= number_to_currency(item.price_sold) %></td>
        <td><%= number_to_currency(item.sold_at) %></td>
        <td><%= item.style.name %></td>
        <td><%= item.clearance_batch_id %></td>
        <td><%= link_to 'Show', item %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @item.id %>
</p>

<p>
  <strong>Size:</strong>
  <%= @item.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @item.color %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>Price sold:</strong>
  <%= @item.price_sold %>
</p>

<p>
  <strong>Sold at:</strong>
  <%= @item.sold_at %>
</p>

<p>
  <strong>Style:</strong>
  <%= @item.style_id %>
</p>

<p>
  <strong>Clearance batch:</strong>
  <%= @item.clearance_batch_id %>
</p>

<%= link_to 'Back', url_for(:back) %>

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg.html_safe, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %h1= link_to 'Stitch Fix Clearance Tool', root_path
    .collapse.navbar-collapse.navbar-right
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Clothing Articles', clothings_path
%li= link_to 'All Items', items_path
%li= link_to 'Custom Upload', manual_input_path, id: 'custom-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeHomeChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= wicked_pdf_stylesheet_link_tag 'application' %>
</head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>